### ISSUE TITLE
Include better method to estimate the nadir 

### ISSUE THREAD

**Issue by frankier** [industrial-optimization-group/DESDEO#23]
e.g. like this paper https://www.iitk.ac.in/kangal/papers/k2005009.pdf

**Comment by ferrety** [comment]
In general, nadir estimation by pay-off table is "good enough".

Approaches such proposed by Deb, Chaudhuri and Miettinen can be used, but those tend to require that the problem is solved in order to find the nadir vector.  At that point, it makes sense to solve the problem using some EMO approach and then examine the non-dominated solution with an interactive method, using, e.g., metamodel.
